services:

  db:
    image: postgres:latest  
    restart: always
    shm_size: 128mb  
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data:
